### ISSUE TITLE
Regarding availability of ground  truth H&E stained test data  

### ISSUE THREAD

**Issue by Sumona-IIITG** [cabooster/UTOM#3]
Hi, 
I am using the autofluorescence and H&E stained dataset. I have trained my network using the dataset. However, I want to test the performance by comparing generated stained with the ground truth test H&E stained dataset.  It will be very helpful if you share the ground truth test H&E stained dataset. I look forward to hearing from you.

**Comment by cabooster** [comment]
Hi, Sumona-IIITG. In our work, we only had adjacent slices for qualitative comparison. We could not obtain pixel-wise registered images because of the destructive preparation. Do you mean adjacent slices with similar histopathological structures?

**Comment by Sumona-IIITG** [comment]
Hi, thank you for the prompt response. Yes I was inquiring about the adjacent slices with similar histological structure. Can you please share adjacent h&e stained  slice for the test autofluorescence images?? So that I could compare my result effectively. I look forward to hearing from you.

**Comment by cabooster** [comment]
You can download our dataset from https://github.com/cabooster/UTOM/blob/master/datasets/README.md
Autofluorescence images and matched adjacent slices can be downloaded from the links in the `Complete dataset` section. The first link is preprocessed images used in our work. The second link is whole-slide pathological images. I hope this helps.

**Comment by Sumona-IIITG** [comment]
Thank you very much. Got the dataset.
